### ISSUE TITLE
Display of env memory limit seems erroneous

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/tljh-repo2docker#14]
I created a new env with these settings:

![image](https://user-images.githubusercontent.com/733861/81066903-1e45db80-8ede-11ea-9d8f-345875a6b731.png)

This env is then proposed to the user with the following properties:

![image](https://user-images.githubusercontent.com/733861/81067018-564d1e80-8ede-11ea-870c-a808addc62cb.png)

The memory limit seems overestimated.

**Comment by pierrepo** [comment]
This issue could impact only 2 GB environments:

![image](https://user-images.githubusercontent.com/733861/81069730-93b3ab00-8ee2-11ea-9842-c42f9e8f721d.png)

![image](https://user-images.githubusercontent.com/733861/81069761-9d3d1300-8ee2-11ea-8494-374087a62803.png)

**Comment by jtpio** [comment]
Good catch, thanks :+1: 

To give more context:

This is because the default memory limit is now set via `tljh-config` in this playbook: https://github.com/plasmabio/plasmabio/blob/b1c8e6d26da368790fe7d8fc04469fe758020587/ansible/tljh.yml#L38-L41

And TLJH sets the values on the `Spawner` here: https://github.com/jupyterhub/the-littlest-jupyterhub/blob/68a84f1f926058142df39a7b4096ed758adf9ac6/tljh/configurer.py#L187

The `mem_limit` trait is defined as a `ByteSpecification` in `jupyterhub`: https://github.com/jupyterhub/jupyterhub/blob/289c3bc3c19951c12cfe540b8245571e299d44aa/jupyterhub/spawner.py#L525-L546

A `ByteSpecification` in `jupyterhub.traitlets` automatically parse the "2G" value into a bytes integer: https://github.com/jupyterhub/jupyterhub/blob/289c3bc3c19951c12cfe540b8245571e299d44aa/jupyterhub/traitlets.py#L90

**Comment by jtpio** [comment]
We can transform this bytes value back into a human readable format before showing it it the user.
